title: Matthew Pieterse # your name (or website title) here
logo: "/images/ca6c7b9f0d8b4e5562745c9e3fa378ff633d2b9af279a2526a7a075d9e0d0dc5.0.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, welcome to my portfolio!
  <br><br>
  South Africa
  <br><br>
  <a href="https://www.example.com/">
   <img alt="Instagram" src="https://img.icons8.com/color/48/000000/instagram.png"
   width=48" height="48">
  </a>
  <a href="https://www.example.com/">
   <img alt="Facebook" src="https://img.icons8.com/color/48/000000/twitter-squared.png"
   width=48" height="48">
  </a>
  <a href="https://www.example.com/">
   <img alt="Twitter" src="https://img.icons8.com/color/48/000000/facebook.png"
   width=48" height="48">
  </a>
  <br><br>
  <a href="https://www.example.com/in/example/">LinkedIn</a> 
theme: jekyll-theme-minimal
google_analytics: G-QBQ4MREBWG # your Google Analytics tracking ID here
